name: Tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python-version: [3.12.7, 3.13.0]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install
      
      - name: static analysis
        run: |
          make mypy
          
      - name: Run tests
        run: |
          make test

      - name: Check for failures
        if: failure()
        run: exit 1          